[sdl]
fullscreen=false
autolock=false

[dosbox]
memsize=16

[cpu]
cycles=max

[autoexec]
mount c /Users/johannes/Downloads/turbo_pascal_701_fr
mount d /Users/johannes/code/retro/retro-game-stream/spikes/001-informed-vibe-code
c:
set PATH=%PATH%;C:\BIN
md D:\BUILD
del D:\*.TPU
TPC.EXE D:\CORPLADR.PAS /UD:\;C:\UNITS /B /OD:\BUILD\ > D:\BUILD\BUILD.LOG
